apiVersion: resource.k8s.io/v1
kind: ResourceSlice
metadata:
  name: counter-slice
spec:
  driver: gpu.intel.com
  pool:
    generation: 1
    name: "my-pool"
    resourceSliceCount: 2
  sharedCounters:
  - name: gpu-0-counter-set
    counters:
      millicores:
        value: 100
---
apiVersion: resource.k8s.io/v1
kind: ResourceSlice
metadata:
  name: device-slice
spec:
  driver: gpu.intel.com
  pool:
    generation: 1
    name: "my-pool"
    resourceSliceCount: 2
  nodeName: "my-node"
  devices:
  - name: gpu-0
    capacity:
      millicores:
        value: 100
    consumesCounters:
    - counterSet: gpu-0-counter-set
      counters:
        millicores:
        value: 100
  - name: gpu-0-partition-0
    capacity:
      millicores:
        value: 100
    consumesCounters:
    - counterSet: gpu-0-counter-set
      counters:
        millicores:
        value: 100
  - name: gpu-0-partition-1
    capacity:
      millicores:
        value: 100
    consumesCounters:
    - counterSet: gpu-0-counter-set
      counters:
        millicores:
        value: 100
  - name: gpu-0-partition-2
    capacity:
      millicores:
        value: 100
    consumesCounters:
    - counterSet: gpu-0-counter-set
      counters:
        millicores:
        value: 100
  - name: gpu-0-partition-3
    capacity:
      millicores:
        value: 100
    consumesCounters:
    - counterSet: gpu-0-counter-set
      counters:
        millicores:
        value: 100
