---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ca.yaml
  - ./cluster.yaml
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./objectstore.yaml
  ## https://github.com/cloudnative-pg/cloudnative-pg/issues/2841
  # - ./pooler.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
  - ./secretstore.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
