[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"

[tools]
"python" = "3.14.3"
"pipx" = "1.8.0"
"pipx:makejinja" = "2.8.2"
"pipx:flux-local" = "8.1.0"
"aqua:budimanjojo/talhelper" = "3.1.3"
"aqua:cilium/cilium-cli" = "0.19.0"
"aqua:cli/cli" = "2.86.0"
"aqua:cloudflare/cloudflared" = "2026.2.0"
"aqua:cue-lang/cue" = "0.15.4"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.48.0"
"aqua:helm/helm" = "4.1.0"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:kubernetes/kubectl" = "1.34.0"
"aqua:mikefarah/yq" = "4.52.2"
"aqua:siderolabs/talos" = "1.12.3"
"aqua:yannh/kubeconform" = "0.7.0"
"aqua:derailed/k9s" = "0.50.18"
"aqua:casey/just" = "1.46.0"
"aqua:charmbracelet/gum" = "0.17.0"
"aqua:wagoodman/dive" = "0.13.1"
"rust" = "1.93.0"
"cargo:minijinja-cli" = "2.13.0"
"github:Handfish/talos-pilot" = "0.1.3"
"aqua:jesseduffield/lazygit" = "0.59.0"
