- Hardware:
    - iDRAC-01:
        href: {{HOMEPAGE_VAR_IDRAC01_URL}}
        description: r730xd iDRAC
        icon: idrac.svg
    - iDRAC-02:
        href: {{HOMEPAGE_VAR_IDRAC02_URL}}
        description: r710 iDRAC
        icon: idrac.svg
    - PowerPanel UPS:
        href: https://ppb-01.local.${SECRET_DOMAIN}/
        description: UPS management
        icon: powerpanel.png

- Virtualization:
    - vSphere:
        href: https://vsphere.local.${SECRET_DOMAIN}/
        description: vCenter Server
        icon: vmware.svg
    - ESXi-01:
        href: https://esxi-01.local.${SECRET_DOMAIN}/
        description: r730xd ESXi Host
        icon: vmware-esxi.svg
    - ESXi-02:
        href: https://esxi-02.local.${SECRET_DOMAIN}/
        description: r710 ESXi Host
        icon: vmware-esxi.svg
    - Portainer-01:
        href: https://portainer-01.local.${SECRET_DOMAIN}/
        description: Primary Portainer instance
        icon: portainer.svg
        widget:
            type: portainer
            url: {{HOMEPAGE_VAR_PORTAINER01_URL}}
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER01_API_KEY}}

- Storage:
    - TrueNAS:
        href: https://nas-01.ad.${SECRET_DOMAIN}/
        description: TrueNAS instance
        icon: truenas.svg
        widget:
            type: truenas
            url: {{HOMEPAGE_VAR_TRUENAS_URL}}
            key: {{HOMEPAGE_VAR_TRUENAS_API_KEY}}
            enablePools: true # optional, defaults to false
            nasType: core # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
    - Longhorn:
        href: https://longhorn.${INTERNAL_SECRET_DOMAIN}
        description: Distributed k3s block storage
        icon: longhorn.svg
    - Kopia:
        href: https://kopia.${INTERNAL_SECRET_DOMAIN}/
        description: Kopia backup management
        icon: kopia.svg
    - Backblaze B2:
        href: https://secure.backblaze.com/b2_buckets.htm
        description: Backblaze B2 cloud storage
        icon: backblaze.svg
    - Cloudflare R2:
        href: {{HOMEPAGE_VAR_CLOUDFLARE_R2_URL}}
        description: Cloudflare R2 cloud storage
        icon: cloudflare.svg

- Internal Services:
    - Home Assistant:
        href: https://homeassistant.local.${SECRET_DOMAIN}/
        description: Home Assistant
        icon: home-assistant.svg
    - Paperless:
        href: https://paperless.${INTERNAL_SECRET_DOMAIN}/
        description: Document management system
        icon: paperless-ngx.svg
        namespace: default # The kubernetes namespace the app resides in
        app: paperless # The name of the deployed app
    - Paperless AI:
        href: https://paperless-ai.${INTERNAL_SECRET_DOMAIN}/
        description: AI interface for paperless
        icon: paperless-ngx.svg
        namespace: default # The kubernetes namespace the app resides in
        app: paperless-ai # The name of the deployed app
    - Syncthing:
        href: https://syncthing.${INTERNAL_SECRET_DOMAIN}/
        description: Syncthing Server on k8s
        icon: syncthing.svg
    - Sunshine:
        href: https://sunshine.local.${SECRET_DOMAIN}/
        description: Sunshine game streaming
        icon: sunshine.svg
    - Windows KMS Server:
        href: https://win-kms.local.${SECRET_DOMAIN}/
        description: Internal Windows KMS Server
        icon: microsoft-windows.svg
    - Lube Logger:
        href: https://lubelogger.${INTERNAL_SECRET_DOMAIN}/
        description: Vehicle maintenance tracker
        icon: lubelogger.svg

- Network:
    - Unifi Cloud Gateway:
        href: https://unifi.local.${SECRET_DOMAIN}/
        description: Unifi Controller instance
        icon: unifi.svg
        widget:
            type: unifi
            url: {{HOMEPAGE_VAR_UNIFI_CONSOLE_URL}}
            username: {{HOMEPAGE_VAR_UNIFI_CONSOLE_USERNAME}}
            password: {{HOMEPAGE_VAR_UNIFI_CONSOLE_PASSWORD}}
    - PiHole-01:
        href: https://pi-01.local.${SECRET_DOMAIN}/admin
        description: Primary PiHole (VM)
        icon: pi-hole.svg
        widget:
            type: pihole
            url: {{HOMEPAGE_VAR_PIHOLE01_URL}}
            # version: 6 # required if running v6 or higher, defaults to 5
            key: {{HOMEPAGE_VAR_PIHOLE01_API_KEY}}
    - PiHole-02:
        href: https://pi-02.local.${SECRET_DOMAIN}/admin
        description: Secondary PiHole (PI)
        icon: pi-hole.svg
        widget:
            type: pihole
            url: {{HOMEPAGE_VAR_PIHOLE02_URL}}
            # version: 6 # required if running v6 or higher, defaults to 5
            key: {{HOMEPAGE_VAR_PIHOLE02_API_KEY}}
    - Nginx Proxy Manager:
        href: https://proxy.local.${SECRET_DOMAIN}/
        description: Reverse proxy instance
        icon: nginx-proxy-manager.svg
    - Cloudflare DNS:
        href: {{HOMEPAGE_VAR_CLOUDFLARE_URL}}
        description: Cloudflare Console
        icon: cloudflare.svg
    - Google Cloud:
        href: {{HOMEPAGE_VAR_GCLOUD_URL}}
        description: Google Cloud DNS Console
        icon: google-cloud-platform.svg

- Observability:
    - Gatus:
        href: https://status.${SECRET_DOMAIN}/
        description: Uptime monitoring dashboard
        icon: gatus.svg
        namespace: observability
        app: gatus
        widget:
            type: gatus
            url: http://gatus.observability.svc.cluster.local:80
    - Grafana:
        href: https://grafana.${INTERNAL_SECRET_DOMAIN}/
        description: Grafana metrics dashboard
        icon: grafana.svg
        namespace: observability
        app: grafana
        # widget:
        #   type: grafana
        #   version: 2
        #   alerts: alertmanager
        #   url: http://grafana-alerting.observability.svc.cluster.local:9094
    - Prometheus:
        href: https://prometheus.${INTERNAL_SECRET_DOMAIN}/
        description: Metrics aggregator
        icon: prometheus.svg
        namespace: observability
        app: prometheus
        widget:
            type: prometheus
            url: http://prometheus-operated.observability.svc.cluster.local:9090
    - Alert Manager:
        href: https://alertmanager.${INTERNAL_SECRET_DOMAIN}/
        description: Alert Manager interface
        icon: alertmanager.svg
        namespace: observability
        app: prometheus
        # widget:
        #   type: prometheus
        #   url: http://prometheushost:port
    - Victoria Logs:
        href: https://victoria-logs.${INTERNAL_SECRET_DOMAIN}/
        description: Log aggregation and viewing
        icon: victoriametrics.svg
        namespace: observability
        app: victoria-logs


- Media:

    - Servers:
        - Plex:
            href: https://plex.${SECRET_DOMAIN}/
            description: Primary Plex server
            icon: plex.svg
        - Emby:
            href: https://emby.${INTERNAL_SECRET_DOMAIN}/
            description: Secondary Emby server
            icon: emby.svg
        - Dispatcharr:
            href: https://dispatcharr.${INTERNAL_SECRET_DOMAIN}/
            description: Live TV management
            icon: dispatcharr.svg
            namespace: default
            app: dispatcharr
        - Calibre Web:
            href: https://ebooks.${SECRET_DOMAIN}/
            description: E-Book library web interface
            icon: calibre-web.svg
            namespace: default
            app: calibre-web-automated
            # widget:
            #   type: calibreweb
            #   url: https://calibre-web.${SECRET_DOMAIN}/
            #   username: MrDynamo
            #   password: {{HOMEPAGE_VAR_CALIBREWEB_PASSWORD}}
        - Calibre GUI:
            href: https://calibre.${INTERNAL_SECRET_DOMAIN}/
            description: Calibre server webui
            icon: calibre.svg
            namespace: default
            app: calibre

    - Management:
        - Tautulli:
            href: https://tautulli.${INTERNAL_SECRET_DOMAIN}/
            description: Plex server streaming statistics
            icon: tautulli.svg
            namespace: default
            app: tautulli
            widget:
                type: tautulli
                url: http://tautulli.default.svc.cluster.local:80
                key: {{HOMEPAGE_VAR_TAUTULLI_API_KEY}}
        - Seerr:
            href: https://plexrequests.${SECRET_DOMAIN}
            description: Media request management
            icon: jellyseerr.svg
            namespace: default
            app: seerr
            widget:
                type: jellyseerr
                url: http://seerr.default.svc.cluster.local:80
                key: {{HOMEPAGE_VAR_SEERR_API_KEY}}
        - Wizarr:
            href: https://joinplex.${SECRET_DOMAIN}/
            description: Plex user management
            icon: wizarr.svg # TODO: Submit for Wizaar icon on walkxcode/dashboard-icons
            namespace: default
            app: wizarr
        - Maintainerr:
            href: https://maintainerr.${INTERNAL_SECRET_DOMAIN}/
            description: Media deletion management
            icon: maintainerr.svg
            namespace: default
            app: maintainerr
        - Your Spotify:
            href: https://spotty.${SECRET_DOMAIN}/
            description: Spotify stats
            icon: spotify.svg
            # namespace: default
            # app: your-spotify
            # widget:
            #   type: yourspotify
            #   url: http://yourspotify.default.svc.cluster.local:80
            #   key: {{HOMEPAGE_VAR_YOURSPOTIFY_API_KEY}}

    - Downloads:
        - SABnzbd:
            href: https://sabnzbd.${INTERNAL_SECRET_DOMAIN}/
            description: NZB download client
            icon: sabnzbd.svg
            namespace: default
            app: sabnzbd
            widget:
                type: sabnzbd
                url: http://sabnzbd.default.svc.cluster.local:80
                key: {{HOMEPAGE_VAR_SABNZBD_API_KEY}}
        - Prowlarr:
            href: https://prowlarr.${INTERNAL_SECRET_DOMAIN}/
            description: Indexer management
            icon: prowlarr.svg
            namespace: default
            app: prowlarr
            widget:
                type: prowlarr
                url: http://prowlarr.default.svc.cluster.local:80
                key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}
        - Sonarr:
            href: https://sonarr.${INTERNAL_SECRET_DOMAIN}/
            description: TV Show management
            icon: sonarr.svg
            namespace: default
            app: sonarr
            widget:
                type: sonarr
                url: http://sonarr.default.svc.cluster.local:80
                key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
                enableQueue: true
        - Radarr:
            href: https://radarr.${INTERNAL_SECRET_DOMAIN}/
            description: Movie management
            icon: radarr.svg
            namespace: default
            app: radarr
            widget:
                type: radarr
                url: http://radarr.default.svc.cluster.local:80
                key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
                enableQueue: true
        - Bazarr:
            href: https://bazarr.${INTERNAL_SECRET_DOMAIN}/
            description: Subtitle management
            icon: bazarr.svg
            namespace: default
            app: bazarr
            widget:
                type: bazarr
                url: http://bazarr.default.svc.cluster.local:80
                key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}
        - Calibre Downloader:
            href: https://calibre-downloader.${INTERNAL_SECRET_DOMAIN}/
            description: E-Book downloader web interface
            icon: calibre-web.svg
            namespace: default
            app: calibre-web-automated

- Database:
    - PGAdmin:
        href: https://pgadmin.local.${SECRET_DOMAIN}/
        description: PostgreSQL management
        icon: pgadmin4.svg
        namespace: database # The kubernetes namespace the app resides in
        app: pgadmin # The name of the deployed app
    - InfluxDB:
        href: https://influxdb.local.${SECRET_DOMAIN}/
        description: InfluxDB time based metrics
        icon: influxdb.svg
        namespace: monitoring
        app: influxdb

- Minecraft:
    - Secret Alliance:
        icon: minecraft.svg
        widget:
            type: minecraft
            url: {{HOMEPAGE_VAR_MINECRAFT_SA_URL}}
    - GT New Horizons:
        icon: minecraft.svg
        widget:
            type: minecraft
            url: {{HOMEPAGE_VAR_UNIFI_CONSOLE_URL}}
