title: DynamicLab Dashboard
headerStyle: boxedWidgets
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
providers:
  longhorn:
    url: http://longhorn-frontend.storage.svc:80
layout:
  Infrastructure:
    syle: row
    columns: 4
    Virtualization:
      syle: row
      columns: 4
  Media:
    syle: row
    columns: 4
    Servers:
      syle: row
      columns: 4
