title: DynamicLab Dashboard
headerStyle: boxedWidgets
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
providers:
  longhorn:
    url: http://longhorn-frontend.storage.svc:80
layout:
  Infrastructure:
    style: row
    columns: 6
    # Hardware:
    #   syle: row
    # Virtualization:
    #   syle: row
    # Storage:
    #   style: row
    # Internal Services:
    #   style: row
    # Network:
    #   style: row
  Media:
    style: row
    columns: 6
    # Servers:
    #   syle: row
    # Management:
    #   style: row
    # Downloads:
    #   style: row
  Observability:
    style: row
  Database:
    style: row
  Minecraft:
    style: row
