title: DynamicLab Dashboard
headerStyle: boxedWidgets
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
providers:
  longhorn:
    url: http://longhorn-frontend.storage.svc:80
layout:
  style: row
#   Infrastructure:
#     style: row
#     columns: 5
#     # Hardware:
#     #   syle: row
#     # Virtualization:
#     #   syle: row
#     # Storage:
#     #   style: row
#     # Internal Services:
#     #   style: row
#     # Network:
#     #   style: row
#     #   columns: 6
#   Media:
#     style: row
#     columns: 3
#     # Servers:
#     #   syle: row
#     #   columns: 5
#     # Management:
#     #   style: row
#     #   columns: 5
#     # Downloads:
#     #   style: row
#     #   columns: 6
#   # Observability:
#   #   style: row
#   # Database:
#   #   style: row
#   # Minecraft:
#   #   style: row
