---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: descheduler
spec:
  groups:
    - name: descheduler
      rules:
        - alert: DeschedulerEvictedPods
          expr: |-
            descheduler_pods_evicted{} > 0
          for: 1m
          keep_firing_for: 15m
          annotations:
            summary: >-
              Descheduler has recently evicted pods on node {{ $labels.node }} due to: {{ $labels.strategy }}.
          labels:
            severity: critical
