---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app dispatcharr
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/dragonfly
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
  dependsOn:
    - name: longhorn
      namespace: storage
  interval: 1h
  path: ./kubernetes/apps/default/dispatcharr/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_SCHEDULE: 0 15 * * 5	  # Cron in UTC (CST: -6, CST: -5)
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app channel-identifiarr
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/volsync
  dependsOn:
    - name: dispatcharr
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/dispatcharr/tools/channel-identifiarr
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_SCHEDULE: 0 15 * * 2 # Cron in UTC (CST: -6, CST: -5)
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app game-thumbs
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: dispatcharr
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/dispatcharr/tools/game-thumbs
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kptv-fast
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: dispatcharr
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/dispatcharr/tools/kptv-fast
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app multiview
#   namespace: &namespace default
# spec:
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   dependsOn:
#     - name: dispatcharr
#       namespace: default
#   interval: 1h
#   path: ./kubernetes/apps/default/dispatcharr/tools/multiview
#   postBuild:
#     substitute:
#       APP: *app
#     substituteFrom:
#       - name: cluster-secrets
#         kind: Secret
#   prune: true
#   retryInterval: 2m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   targetNamespace: *namespace
#   timeout: 5m
#   wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app streamflow
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/volsync
  dependsOn:
    - name: dispatcharr
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/dispatcharr/tools/streamflow
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_SCHEDULE: 0 15 * * 2 # Cron in UTC (CST: -6, CST: -5)
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app teamarr
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/volsync
  dependsOn:
    - name: dispatcharr
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/dispatcharr/tools/teamarr
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_SCHEDULE: 0 15 * * 2 # Cron in UTC (CST: -6, CST: -5)
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app webpage-hls
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: dispatcharr
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/dispatcharr/tools/webpage-hls
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app enhanced-channel-manager
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/volsync
  dependsOn:
    - name: dispatcharr
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/dispatcharr/tools/enhanced-channel-manager
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_SCHEDULE: 0 15 * * 2 # Cron in UTC (CST: -6, CST: -5)
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app emby-logos
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: dispatcharr
      namespace: default
  interval: 1h
  path: ./kubernetes/apps/default/dispatcharr/tools/emby-logos
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
