---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ./cert
  # - ./cert/certificate.yaml
  # - ./cert/secret.yaml
  # - ./pass
  # - ./pass/externalsecret.yaml
  - ./patch
  # - ./patch/kustomization.yaml
  - ./postgres
  # - ./postgres/database.yaml
  - ./ks.yaml
