---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ./cert/certificate.yaml
  - ./cert/secret.yaml
  - ./pass/externalsecret.yaml
  - ./patch/kustomization.yaml
  - ./postgres/database.yaml
