---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  # - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: streamflow
    files:
      - automation_config.json=./resources/automation_config.json
      - channel_regex_config.json=./resources/channel_regex_config.json
      - stream_checker_config.json=./resources/stream_checker_config.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
