---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kometa
spec:
  chartRef:
    kind: OCIRepository
    name: kometa
  interval: 1h
  values:
    controllers:
      kometa:
        type: cronjob
        cronjob:
          ##
          ##     For UTC Time - https://crontab.guru/
          ##     CST: -6
          ##     CDT: -5
          ##
          ##     0 11 * * * (UTC)     Daily at 5am or 6am
          ##
          schedule: 0 6 * * *
          timeZone: &TZ America/Chicago
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 86400
        containers:
          app:
            image:
              repository: docker.io/kometateam/kometa
              tag: v2.2.2@sha256:32992226d1a505da3ed5d4e9c97bed8a6deb7aef36cd5ef8b1f519762607df45
            env:
              TZ: *TZ
              ##### Targeted runs - Uncomment to activate
              ## Run only testing libraries
              # KOMETA_RUN_LIBRARIES: "pmm_mov|pmm_tv"
              ## Run only collections on all libraries
              KOMETA_COLLECTIONS_ONLY: true
              ## Run only overlays on all libraries
              # KOMETA_OVERLAYS_ONLY: true
              #####
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            args: [ "--read-only-config", "--width 200", "--run" ]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
        pod:
          restartPolicy: Never
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      media:
        type: nfs
        server: 192.168.20.21
        path: /mnt/tank/media/plex
        globalMounts:
          - path: /config/assets
            subPath: assets
      configmap:
        type: configMap
        name: kometa
        advancedMounts:
          kometa:
            app:
              - path: /config/config.yml
                subPath: config.yml
              - path: /config/movies.yaml
                subPath: movies.yaml
              - path: /config/tv.yaml
                subPath: tv.yaml
              - path: /config/remove-overlays.yaml
                subPath: remove-overlays.yaml
      tmp:
        type: emptyDir
