---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/alerts
  - ../../components/common
resources:
  - ./atuin/ks.yaml
  - ./bazarr/ks.yaml
  - ./calibre/ks.yaml
  - ./calibre-web-automated/ks.yaml
  - ./calibre-web-downloader/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./emby/ks.yaml
  - ./homepage/ks.yaml
  - ./invoiceninja/ks.yaml
  - ./kometa/ks.yaml
  - ./lubelogger/ks.yaml
  - ./maintainerr/ks.yaml
  - ./mealie/ks.yaml
  - ./open-webui/ks.yaml
  - ./paperless/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
  - ./syncthing/ks.yaml
  - ./tautulli/ks.yaml
  - ./wizarr/ks.yaml
  - ./your-spotify/ks.yaml
