---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app emby-logos
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      emby-logos:
        # initContainers:
        #   add-passwd:
        #     image:
        #       repository: busybox
        #       tag: 1.37.0@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
        #     command:
        #       - sh
        #       - -c
        #       - |
        #         cp /etc/passwd /work/passwd || true
        #         echo 'emby:x:1000:1000:Emby User:/home/emby:/sbin/nologin' >> /work/passwd
        #         chmod 0644 /etc/passwd
        containers:
          app:
            image:
              repository: ghcr.io/sethwv/emby-logo-tools
              tag: latest@sha256:caa355adc004362ebe13322068f354e2a80164e131b2d087be4334175285f0ce
            env:
              TZ: America/Chicago
              EMBY_SERVER_URL: http://emby.default.svc:8096
              MODE: copy
              DRY_RUN: true
              FIRST_ONLY: false
              FORCE: false
              TAGS: "NEWS,ENTERTAINMENT"
              LIST_TAGS: false
              DEBUG_TAGS: false
              CRON_SCHEDULE: "0 3 * * *"
              RUN_ONCE: false
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
            - path: /var/log
              subPath: log
            - path: /var/spool/cron
              subPath: spool-cron
            - path: /etc/cron.d
              subPath: cron.d
      passwd:
        type: configMap
        name: *app
        defaultMode: 0664
        globalMounts:
          - path: /etc/passwd
            subPath: passwd
