---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: shulker
  namespace: shulker-system
spec:
  interval: 15m
  url: https://github.com/jeremylvln/Shulker
