---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shulker
spec:
  interval: 1h
  chart:
    spec:
      chart: shulker-operator
      sourceRef:
        kind: HelmRepository
        name: shulker
      version: 0.13.0
  values:
    operator:
      agones:
        allocator:
          host: agones-alocator.shulker-system.svc
          grpcPort: 443
          mtlsSecretName: allocator-client.default
