---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: your-spotify
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: your-spotify-secret
    template:
      data:
        SPOTIFY_PUBLIC: "{{ .SPOTIFY_CLIENT_ID }}"
        SPOTIFY_SECRET: "{{ .SPOTIFY_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: your-spotify
