apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: lobby
spec:
  clusterRef:
    name: getting-started
  replicas: 1
  template:
    spec:
      clusterRef:
        name: getting-started
      tags:
        - lobby
      version:
        channel: Paper
        name: '1.21.1'
      config: {}
      podOverrides:
        image:
          name: "ghcr.io/itzg/minecraft-server:latest@sha256:ae77caa9920f0a0e83a8ba403fc9e8005d9e4e82bae3056f55520a147be6553c"
        env:
          - name: MEMORY
            value: "2G"
          - name: OVERRIDE_SERVER_PROPERTIES
            value: "true"
          - name: MOTD
            value: "Shulker test"
