apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: lobby
spec:
  clusterRef:
    name: mc-cluster
  replicas: 1
  template:
    spec:
      clusterRef:
        name: mc-cluster
      tags:
        - lobby
      version:
        channel: Paper
        name: '1.21.1'
      config: {}
      podOverrides:
        image:
          name: "ghcr.io/itzg/minecraft-server:2025.12.0@sha256:4eb78cc5f3f4e87e281d38590deca2a4a74afaa9f351210059cb2786443994f2"
        env:
          - name: MEMORY
            value: "2G"
          - name: OVERRIDE_SERVER_PROPERTIES
            value: "true"
          - name: MOTD
            value: "Shulker Test"
