apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet
metadata:
  name: mc-proxy-public
spec:
  clusterRef:
    name: mc-cluster
  replicas: 1
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  template:
    spec:
      version:
        channel: Velocity
        name: latest
      config: {}
      podOverrides:
        image:
          name: "ghcr.io/itzg/mc-proxy:latest@sha256:d361e2c1cbe14d9ccf349322c7674b89967af015cde0d721698be7be3bd2c471"
