---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pihole-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: pihole
    envFrom:
      - secretRef:
        name: "{{ .Release.Name }}-secret"
    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=internal
      # - --pihole-api-version=6
    triggerLoopOnEvent: true
    policy: upsert-only
    sources: ["crd", "gateway-httproute"]
    registry: noop
    domainFilters: ["${INTERNAL_SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
