---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: invoiceninja
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: invoiceninja-secret
    template:
      data:
        APP_KEY: "{{ .LARAVEL_APP_KEY }}"
        IN_USER_EMAIL: "{{ .INITIAL_ADMIN_USER_EMAIL }}"
        IN_PASSWORD: "{{ .INITIAL_ADMIN_USER_PASS }}"
  dataFrom:
    - extract:
        key: invoiceninja
