---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./helmrepository.yaml
  - ./runtimeclass.yaml
configMapGenerator:
  - name: nvidia-k8s-device-plugin-configmap
    files:
      - shared-p400.yaml=./resources/shared-p400.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
