---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app longhorn
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: longhorn
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    persistence:
      defaultClass: false
      defaultDataLocality: best-effort
    defaultSettings:
      allowRecurringJobsWhileVolumeDetached: "true"
      createDefaultDiskLabeledNodes: "true"
      defaultDataLocality: "best-effort"
      defaultDataPath: "/var/lib/longhorn"
      defaultLonghornStaticStorageClass: "longhorn-static"
      defaultReplicaCount: "3"
      # guaranteedInstanceManagerCPU: 20
      nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
      offlineReplicaRebuilding: "enabled"
      orphanAutoDeletion: "true"
      replicaAutoBalance: "least-effort"
      storageMinimalAvailablePercentage: "5"
      storageReservedPercentageForDefaultDisk: "15"
    ingress:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: true
        # relabelings:
        #   - sourceLabels: [__meta_kubernetes_pod_container_name, __meta_kubernetes_pod_container_port_number]
        #     regex: 'longhorn-manager;9500'
        #     action: keep
