kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
retentionPolicy: Retain
parameters:
  dataLocality: "best-effort"
  numberOfReplicas: "2"
  staleReplicaTimeout: "480" # 8 hours in minutes
