---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    template:
      data:
        HOMEPAGE_VAR_PORTAINER01_URL: "{{ .HOMEPAGE_PORTAINER01_URL }}"
        HOMEPAGE_VAR_PORTAINER01_API_KEY: "{{ .HOMEPAGE_PORTAINER01_API_KEY }}"
        HOMEPAGE_VAR_IDRAC01_URL: "{{ .HOMEPAGE_IDRAC01_URL }}"
        HOMEPAGE_VAR_IDRAC02_URL: "{{ .HOMEPAGE_IDRAC02_URL }}"
        HOMEPAGE_VAR_TRUENAS_URL: "{{ .HOMEPAGE_TRUENAS_URL }}"
        HOMEPAGE_VAR_TRUENAS_API_KEY: "{{ .HOMEPAGE_TRUENAS_API_KEY }}"
        HOMEPAGE_VAR_UNIFI_CONSOLE_URL: "{{ .HOMEPAGE_UNIFI_CONSOLE_URL }}"
        HOMEPAGE_VAR_UNIFI_CONSOLE_USERNAME: "{{ .HOMEPAGE_UNIFI_CONSOLE_USERNAME }}"
        HOMEPAGE_VAR_UNIFI_CONSOLE_PASSWORD: "{{ .HOMEPAGE_UNIFI_CONSOLE_PASSWORD }}"
        HOMEPAGE_VAR_PIHOLE01_URL: "{{ .HOMEPAGE_PIHOLE01_URL }}"
        HOMEPAGE_VAR_PIHOLE01_API_KEY: "{{ .HOMEPAGE_PIHOLE01_API_KEY }}"
        HOMEPAGE_VAR_PIHOLE02_URL: "{{ .HOMEPAGE_PIHOLE02_URL }}"
        HOMEPAGE_VAR_PIHOLE02_API_KEY: "{{ .HOMEPAGE_PIHOLE02_API_KEY }}"
        HOMEPAGE_VAR_CLOUDFLARE_URL: "{{ .HOMEPAGE_CLOUDFLARE_URL }}"
        HOMEPAGE_VAR_GCLOUD_URL: "{{ .HOMEPAGE_GCLOUD_URL }}"
        HOMEPAGE_VAR_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
        HOMEPAGE_VAR_SEERR_API_KEY: "{{ .SEERR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_API_KEY: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_BAZARR_API_KEY: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_READARR_API_KEY: "{{ .READARR_API_KEY }}"
        HOMEPAGE_VAR_CALIBREWEB_PASSWORD: "{{ .HOMEPAGE_CALIBREWEB_PASSWORD }}"
        HOMEPAGE_VAR_MINECRAFT_SA_URL: "{{ .HOMEPAGE_MINECRAFT_SA_URL }}"
        HOMEPAGE_VAR_MINECRAFT_GTNH_URL: "{{ .HOMEPAGE_MINECRAFT_GTNH_URL }}"
        HOMEPAGE_VAR_CLOUDFLARE_R2_URL: "{{ .HOMEPAGE_CLOUDFLARE_R2_URL }}"
  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: tautulli
    - extract:
        key: seerr
    - extract:
        key: sabnzbd
    - extract:
        key: prowlarr
    - extract:
        key: sonarr
    - extract:
        key: radarr
    - extract:
        key: bazarr
    - extract:
        key: readarr
