apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vCxCRnRChcamwdi7eok=,iv:PS3knioFGpWv51x86aJLPR6mZYBAFXnCBOykjiqOflc=,tag:kZAdKMnbdnED5VgiuUYVdQ==,type:str]
  INTERNAL_SECRET_DOMAIN: ENC[AES256_GCM,data:icpzw36OLqv36UhP93zCoJPYIRMYykk=,iv:4kxW0fO2RZf+IAI+7NXg8OWe34XD4cB+rlKTF/uLkyk=,tag:Ly5iw+gQkzzKqkLnxNRcPQ==,type:str]
  DYNAMIC_DNS: ENC[AES256_GCM,data:/OHlXlBDT5sq/YVaKVXX+vS6/wzJKw==,iv:pEsI/WztlJr7JaARkvJ1P8SM2NgbziSp2lHG5MuVUSQ=,tag:z4dXqHuYFH7WStbOc/HDgA==,type:str]
  VPS_DYNAMIC_DNS: ENC[AES256_GCM,data:ccgtj4MV5GsCmPpN/2r9nAO46Y3rowyhT6Ei9iA=,iv:gaaBv+CHC51zpgTJt2WNVkeUOKk4KULmYojEbvKLEAY=,tag:kxDQ2GuyA/zcDBLLW+0ziQ==,type:str]
sops:
  age:
    - recipient: age1yum2rd54mjqlzzpklr209h8qukjngtj5pnn74ugwntzkl6d9fvfqrrzmns
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmK1Z0NGRMcGFyKy9wZ3V0
        K29sZTJxbkdKc3lzUkhmL2VXMjlVNUhkUTEwClhHejVDMnhjOUtlZElkSUowVVNW
        cFZMa3NsM3I2d3RGYmxzTHRhTGx3OUEKLS0tIHNvZFNPa2diMUJjdlRnUzhBdnc3
        aFZiZ2NPcmVJYWVRUGkxbG4yWjY1WkUKIQsBDMLGEKV/p8SJ2eyfmx3zEStOiCwu
        YFf8Uoe0yiiX29u+kUHzHg4vk9laIsj9PYBRH+j4TMAN1lPmWykTfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T19:35:33Z"
  mac: ENC[AES256_GCM,data:TRcvELKovjZoLp/UwQdVDZ7tGE0mth1v0lgNcefRJclhyYiP1z1wdQY1UX+/Jsp3zqy5u3lPn7DeneeAwsjX1D1wbaj/YK/o/2ruqhbpmafLeGgBqOCWWspzPXOvtmr4qzJbh9MFMbCNd7PlISg7ZUDujybGRxMDVhFV2hj2IRI=,iv:iCrhtHLlTT+OOZ8ZUBFSRqqBhU6FzlroljZaR/TBRJc=,tag:+z7cEdS8tkHwUkIuHyrnEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
